#!/usr/bin/env bash
# update-code-pins.sh — regenerate the code-integrity pins both browser extensions
# ship (firefox-extension/code-pins.js and chrome-extension/code-pins.js).
#
# Each extension is locally-installed code the server cannot rewrite, so it is the
# trust anchor for the one hole the in-page vm2 integrity manifest can't cover: a
# compromised server that swaps the served javascript.js (the manifest signs vault
# *data*, not the app *code*). On unlock the extension fetches the vault's served
# javascript.js + argon2-worker.js and compares each file's SHA-256 against the pin
# written here (see vault-session.js → _verifyCode); a mismatch warns and disables
# autofill.
#
# Run this on EVERY release, AFTER javascript.js is final (its bytes are what the
# server serves verbatim). It has no npm dependency — just sha256sum + node for the
# version string.
set -euo pipefail
cd "$(dirname "$0")"

VERSION="$(node -p "require('./manifest.json').version")"
JS_HASH="$(sha256sum javascript.js | cut -d' ' -f1)"
AW_HASH="$(sha256sum argon2-worker.js | cut -d' ' -f1)"

for ext in firefox-extension chrome-extension; do
  cat > "$ext/code-pins.js" <<EOF
// code-pins.js — GENERATED by ../update-code-pins.sh; do not edit by hand.
//
// SHA-256 of the vault's served code assets, pinned so the extension can detect a
// server that swapped the app bundle (the one thing the in-page vm2 manifest can't
// catch — it signs vault data, not code). Bumped on every release.
globalThis.VAULT_CODE_PINS = {
  version: "$VERSION",
  hashes: {
    "javascript.js": "$JS_HASH",
    "argon2-worker.js": "$AW_HASH",
  },
};
EOF
done

echo "Pinned code assets (v$VERSION):"
echo "  javascript.js     $JS_HASH"
echo "  argon2-worker.js  $AW_HASH"
echo
echo "Wrote firefox-extension/code-pins.js and chrome-extension/code-pins.js"
