// code-pins.js — GENERATED by ../update-code-pins.sh; do not edit by hand.
//
// SHA-256 of the vault's served code assets, pinned so the extension can detect a
// server that swapped the app bundle (the one thing the in-page vm2 manifest can't
// catch — it signs vault data, not code). Bumped on every release.
globalThis.VAULT_CODE_PINS = {
  version: "1.1.11",
  hashes: {
    "javascript.js": "09dc0959079d24c9a3bf94f48f8c12e9134021387561dbc395ec4b7451c5e36a",
    "argon2-worker.js": "859bf1eade4c36a5f68de379e348084383014e773effbfd63a97fc0a2e4e925d",
  },
};
